### ISSUE TITLE
Unable to clone this project ! 

### ISSUE THREAD

**Issue by himurali** [StaticMania/roxo-eleventy#1] opened 2022-02-05 16:29 UTC
Unable to clone this project ! 

![image](https://user-images.githubusercontent.com/20871807/152650079-a24ee7f2-7b05-46cd-bcc5-b19a9b180adb.png)

**Comment by sizious** [comment] 2022-09-27 20:55
Hello,
Indeed I had the same issue. This is due to that filename: [design-inspiration:the-best-projects-from-November.md](https://github.com/StaticMania/roxo-eleventy/blob/master/src/blog/design-inspiration:the-best-projects-from-November.md). The colons character is invalid on Windows OS. If you rename this file in your cloned repository on GitHub it will solve the issue.

**Comment by tanvirpiash** [comment] 2022-09-28 06:58
Renamed the file name as @sizious suggested. Hope the issue is fixed by now.

**Closed as completed** 2022-09-28 06:58 UTC
